apiVersion: v1
kind: Pod
metadata: 
  name: nginx-config
  labels: 
   app: pod-nginx-config
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: config-value-custom
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_MODE
      ports:
        - name: container-port
          protocol: TCP
          containerPort: 80