apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-demo-rc
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-demo
      labels:
        app: nginx
        enviroment: production
        release: v1.0
    spec:
      containers:
        - name: write-container
          image: alpine
          command: ['/bin/sh']
          args: ['-c','while true; do date >> /var/log/index.html; sleep 10; done']
          volumeMounts:
            - name: shared-data
              mountPath: /var/log/
        - name: serve-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name : shared-data
              mountPath: /usr/share/nginx/html
      volumes:
       - name: shared-data
         emptyDir: {}

