apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "env; sleep 3600"]
    env:
    - name: TLS-CERT
      valueFrom:
        secretKeyRef:
          name: tls-secret
          key: tls.crt
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
