apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: app
    image: nginx
    envFrom:
      - secretRef:
          name: my-secret   # imports all keys as env vars
    env:
      - name: MY_NAME
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: name  # imports just 'password' as SPECIAL_PASSWORD env var
