apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-demo-rs
  labels:
    app: nginx
    enviroment: production
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: [nginx, demo]
      - {key: release, operator: In, values: [v1.0, v1.1]}
  template:
    metadata:
      name: nginx-demo
      labels:
        app: demo
        enviroment: production
        release: v1.1
    spec:
      containers:
        - name: write-container
          image: alpine
          command: ['/bin/sh']
          args: ['-c','while true; do date >> /var/log/index.html; sleep 10; done']
          volumeMounts:
            - name: shared-data
              mountPath: /var/log/
        - name: serve-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name : shared-data
              mountPath: /usr/share/nginx/html
      volumes:
       - name: shared-data
         emptyDir: {}

