apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    # app: demo
    env: prod
    app: nginx
    release: v1.0
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: nginx-data
          mountPath: /var/www/html
      env:
        - name: USER_DETAIL
          value: "Nikhil"
      resources:
        limits:
          cpu: "500m"
          memory: "500Mi"
        requests:
          cpu: "200m"
          memory: "200Mi"
  volumes: 
    - name: nginx-data
      emptyDir: {}